[package]
name = "rust-ekf"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ekf_batch"
path = "src/main.rs"

[dependencies]
nalgebra = "0.33.2"
polars = "0.49.1"

[dev-dependencies]
approx = "0.5"
